# Generated by Django 6.0.8 on 2026-09-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('agent', 'Agent'), ('user', 'User')], default='user', help_text='Role in the HYPAX platform', max_length=20),
        ),
    ]
