# Generated by Django 6.0.8 on 2026-09-09 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_city_profile_country_profile_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='street',
        ),
    ]
