# Generated by Django 6.0.8 on 2026-09-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_city_remove_profile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notification_pref',
            field=models.CharField(choices=[('email', 'By Email'), ('hypax', 'In HYPAX')], default='email', help_text='How the account owner wants to receive notifications.', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('system', 'System'), ('light', 'Light'), ('dark', 'Dark')], default='system', help_text='UI theme: follow the system, or force light/dark.', max_length=20),
        ),
    ]
