# Generated by Django 6.0.8 on 2026-09-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_notification_pref_profile_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='font_pref',
            field=models.CharField(choices=[('default', 'Default'), ('inter', 'Inter'), ('poppins', 'Poppins'), ('outfit', 'Outfit'), ('manrope', 'Manrope'), ('space_grotesk', 'Space Grotesk'), ('exo_2', 'Exo 2'), ('plus_jakarta', 'Plus Jakarta Sans')], default='default', help_text='Web font applied to the whole platform for this account.', max_length=30),
        ),
    ]
