# Generated by Django 6.0.8 on 2026-09-12 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_font_pref'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='agent_commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Agent commission percentage (0-100).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_number',
            field=models.CharField(blank=True, default='', help_text='Government ID number', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_type',
            field=models.CharField(blank=True, choices=[('passport', 'Passport'), ('nida', 'NIDA'), ('driver_license', 'Driver License')], default='', help_text='Kind of government ID held by the account owner (e.g. NIDA).', max_length=30),
        ),
    ]
