# Generated by Django 6.0.8 on 2026-09-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(help_text='e.g. https://example.com', max_length=500)),
                ('auth_type', models.CharField(choices=[('none', 'No Auth'), ('bearer', 'Bearer Token'), ('basic', 'Basic Auth')], default='bearer', max_length=20)),
                ('api_token', models.CharField(blank=True, help_text='Token used for Bearer authentication', max_length=500)),
                ('username', models.CharField(blank=True, max_length=200)),
                ('password', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_loading', models.CharField(max_length=255)),
                ('route_delivery', models.CharField(max_length=255)),
                ('customer', models.CharField(max_length=200)),
                ('cargo_type', models.CharField(choices=[('container_20', 'Container 20ft'), ('container_40', 'Container 40ft'), ('break_bulk', 'Break Bulk'), ('bulk', 'Bulk'), ('dry_van', 'Dry Van'), ('reefer', 'Reefer')], max_length=50)),
                ('truck_type', models.CharField(choices=[('trailer', 'Trailer'), ('flatbed', 'Flatbed'), ('truck', 'Truck'), ('sideloader', 'Sideloader'), ('lowbed', 'Lowbed')], max_length=50)),
                ('weight', models.FloatField()),
                ('number_of_trucks', models.PositiveIntegerField()),
                ('distance_km', models.FloatField()),
                ('cargo_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
