# Generated by Django 6.0.8 on 2026-09-06 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0003_alter_tender_route_delivery_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='cargo_reference',
            field=models.CharField(blank=True, default='', help_text='Reference returned by the external system (e.g. CAR00014)', max_length=200),
        ),
        migrations.AddField(
            model_name='tender',
            name='external_id',
            field=models.BigIntegerField(blank=True, help_text='ID returned by the external system', null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='external_status',
            field=models.CharField(blank=True, default='', help_text='Status returned by the external system', max_length=50),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveBigIntegerField(unique=True)),
                ('order_name', models.CharField(blank=True, default='', max_length=255)),
                ('state', models.CharField(blank=True, default='', max_length=50)),
                ('company_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('date_order', models.DateTimeField(blank=True, null=True)),
                ('amount_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('customer', models.CharField(blank=True, default='', max_length=255)),
                ('currency', models.CharField(blank=True, default='', max_length=10)),
                ('cargo_reference', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('cargo_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='tenders.tender')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.PositiveBigIntegerField()),
                ('product_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('price_unit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('price_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('price_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenders.order')),
            ],
        ),
    ]
