# Generated by Django 6.0.8 on 2026-09-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0004_tender_cargo_reference_tender_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='award_response',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='awarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
