# Generated by Django 6.0.8 on 2026-09-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0005_order_award_response_order_awarded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='awarded',
            field=models.BooleanField(default=False, help_text='Marked when this order line is confirmed/awarded'),
        ),
    ]
