# Generated by Django 6.0.8 on 2026-09-07 10:54

import random
import string

from django.db import migrations, models


def backfill_aliases(apps, schema_editor):
    Order = apps.get_model('tenders', 'Order')
    existing = set(Order.objects.exclude(transporter_alias='').values_list('transporter_alias', flat=True))
    for order in Order.objects.filter(transporter_alias=''):
        while True:
            alias = ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(8))
            if not (any(c.isalpha() for c in alias) and any(c.isdigit() for c in alias)):
                continue
            if alias in existing:
                continue
            existing.add(alias)
            order.transporter_alias = alias
            order.save(update_fields=['transporter_alias'])
            break


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0006_orderline_awarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transporter_alias',
            field=models.CharField(blank=True, default='', help_text='Random anonymous alias shown instead of the transporter name', max_length=40),
        ),
        migrations.RunPython(backfill_aliases),
    ]
