# Generated by Django 6.0.8 on 2026-09-07 17:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0009_town_postgis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='town',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Geographic location (longitude, latitude)', srid=4326),
        ),
    ]
