# Generated by Django 6.0.8 on 2026-09-07 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0010_alter_town_point'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-date_order', '-created_at'], name='order_dates_idx'),
        ),
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(fields=['order', 'awarded'], name='orderline_order_awarded_idx'),
        ),
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(fields=['awarded'], name='orderline_awarded_idx'),
        ),
    ]
