# Generated by Django 6.0.8 on 2026-09-07 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0012_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='company',
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.PositiveBigIntegerField(blank=True, help_text='ID of the transport company in the external system', null=True)),
                ('company_name', models.CharField(blank=True, default='', help_text='Name of the transport company', max_length=255)),
                ('alias', models.CharField(blank=True, default='', help_text='Anonymous alias shown instead of the transporter name', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agents', models.ManyToManyField(blank=True, help_text="Agents that can see this transporter's tenders, orders and invoices", related_name='linked_transporters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_name', 'alias'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='transporter',
            field=models.ForeignKey(blank=True, help_text='Transport company this invoice is issued to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='tenders.transporter'),
        ),
    ]
