# Generated by Django 6.0.8 on 2026-09-07 22:20

from django.db import migrations


def consolidate_shared_setting(apps, schema_editor):
    ApiSetting = apps.get_model('tenders', 'ApiSetting')
    CustomUser = apps.get_model('users', 'CustomUser')
    admin_ids = set(
        CustomUser.objects.filter(role='administrator').values_list('pk', flat=True)
    )
    rows = list(ApiSetting.objects.all())
    if not rows:
        return
    keep = next((r for r in rows if r.user_id in admin_ids), None) or rows[0]
    ApiSetting.objects.exclude(pk=keep.pk).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0013_remove_invoice_company_transporter_and_more'),
        ('users', '0005_create_roles_groups_admin'),
    ]

    operations = [
        migrations.RunPython(consolidate_shared_setting, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='apisetting',
            name='user',
        ),
    ]