# Generated by Django 6.0.8 on 2026-09-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0014_remove_apisetting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='apisetting',
            name='selcom_base_url',
            field=models.CharField(blank=True, help_text='Optional Selcom API root. Defaults to sandbox or production APIGW.', max_length=500),
        ),
        migrations.AddField(
            model_name='apisetting',
            name='selcom_client_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='apisetting',
            name='selcom_client_secret',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='apisetting',
            name='selcom_currency',
            field=models.CharField(blank=True, default='TZS', max_length=10),
        ),
        migrations.AddField(
            model_name='apisetting',
            name='selcom_enabled',
            field=models.BooleanField(default=False, help_text='Enable Selcom payment gateway for invoice payments.'),
        ),
        migrations.AddField(
            model_name='apisetting',
            name='selcom_paylink_base',
            field=models.CharField(blank=True, help_text='Optional hosted checkout root. Defaults to the Selcom API root.', max_length=500),
        ),
        migrations.AddField(
            model_name='apisetting',
            name='selcom_payment_methods',
            field=models.CharField(blank=True, help_text='Comma-separated wallets/banks, e.g. MPESA,TIGOPESA,AIRTELMONEY,HALOPESA,CRDB,NMB', max_length=500),
        ),
        migrations.AddField(
            model_name='apisetting',
            name='selcom_sales_channel',
            field=models.CharField(blank=True, help_text='Sales channel / vendor name, e.g. PURCHASE.', max_length=100),
        ),
        migrations.AddField(
            model_name='apisetting',
            name='selcom_sandbox',
            field=models.BooleanField(default=True, help_text='Use Selcom sandbox (apigwdev) endpoints. Disable for production.'),
        ),
        migrations.AddField(
            model_name='apisetting',
            name='selcom_webhook_secret',
            field=models.CharField(blank=True, help_text='Shared secret used to verify Selcom payment callback signatures.', max_length=500),
        ),
        migrations.AddField(
            model_name='invoice',
            name='selcom_order_token',
            field=models.CharField(blank=True, default='', help_text='Order token returned by Selcom when the checkout order was created', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='selcom_pay_link',
            field=models.CharField(blank=True, default='', help_text='Hosted checkout URL for the invoice payment', max_length=600),
        ),
        migrations.AddField(
            model_name='invoice',
            name='selcom_reference',
            field=models.CharField(blank=True, default='', help_text='Vendor reference used when creating the Selcom checkout order', max_length=120),
        ),
        migrations.AddField(
            model_name='invoice',
            name='selcom_status',
            field=models.CharField(blank=True, default='', help_text='Latest payment status reported by Selcom', max_length=40),
        ),
        migrations.AddField(
            model_name='invoice',
            name='selcom_updated_at',
            field=models.DateTimeField(blank=True, help_text='When the Selcom payment status was last checked', null=True),
        ),
    ]
