# Generated by Django 6.0.8 on 2026-09-08 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0015_apisetting_selcom_base_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, default='', max_length=120)),
                ('license_plate', models.CharField(blank=True, default='', max_length=40)),
                ('tags', models.CharField(blank=True, default='', max_length=200)),
                ('chassis_number', models.CharField(blank=True, default='', max_length=120)),
                ('model_year', models.PositiveIntegerField(blank=True, null=True)),
                ('tonnage_capacity', models.FloatField(blank=True, help_text='Tonnage capacity (tonnes)', null=True)),
                ('number_of_axles', models.PositiveIntegerField(blank=True, null=True)),
                ('volume_capacity', models.FloatField(blank=True, help_text='Volume capacity for tanks (cubic metres)', null=True)),
                ('truck_type', models.CharField(blank=True, choices=[('trailer', 'Trailer'), ('flatbed', 'Flatbed'), ('truck', 'Truck'), ('sideloader', 'Sideloader'), ('lowbed', 'Lowbed')], default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to='tenders.transporter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
