# Generated by Django 6.0.8 on 2026-09-08 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0016_truck'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=150)),
                ('vehicle_type', models.CharField(blank=True, choices=[('trailer', 'Trailer'), ('flatbed', 'Flatbed'), ('truck', 'Truck'), ('sideloader', 'Sideloader'), ('lowbed', 'Lowbed')], default='', max_length=50)),
                ('model_year', models.PositiveIntegerField(blank=True, null=True)),
                ('volume_capacity', models.FloatField(blank=True, help_text='Volume capacity for tanks (cubic metres)', null=True)),
                ('tonnage_capacity', models.FloatField(blank=True, help_text='Tonnage capacity (tonnes)', null=True)),
                ('number_of_axles', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(blank=True, choices=[('diesel', 'Diesel'), ('petrol', 'Petrol / Gasoline'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('cng', 'CNG / LPG')], default='', max_length=20)),
                ('transmission', models.CharField(blank=True, choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('amt', 'Automated Manual (AMT)')], default='', max_length=20)),
                ('drive_type', models.CharField(blank=True, choices=[('4x2', '4x2'), ('4x4', '4x4'), ('6x2', '6x2'), ('6x4', '6x4'), ('8x4', '8x4'), ('awd', 'AWD')], default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['manufacturer', 'name'],
            },
        ),
        migrations.AddField(
            model_name='truck',
            name='truck_model',
            field=models.ForeignKey(blank=True, help_text='Optionally links this truck to a catalog model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trucks', to='tenders.truckmodel'),
        ),
    ]
