# Generated by Django 6.0.8 on 2026-09-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0017_truckmodel_truck_truck_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='apisetting',
            name='email_host',
            field=models.CharField(blank=True, default='imap.gmail.com', max_length=255),
        ),
        migrations.AddField(
            model_name='apisetting',
            name='email_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='apisetting',
            name='email_port',
            field=models.IntegerField(default=993),
        ),
        migrations.AddField(
            model_name='apisetting',
            name='email_use_ssl',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apisetting',
            name='email_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
