# Generated by Django 6.0.8 on 2026-09-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0018_apisetting_email_host_apisetting_email_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apisetting',
            name='email_from',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='apisetting',
            name='smtp_host',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='apisetting',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='apisetting',
            name='smtp_port',
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name='apisetting',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apisetting',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apisetting',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
