# Generated by Django 6.0.8 on 2026-09-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0019_apisetting_email_from_apisetting_smtp_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apisetting',
            name='media_storage',
            field=models.CharField(choices=[('local', 'Option A - Server volume'), ('s3', 'Option B - S3 object storage')], default='local', help_text='Where uploaded files (profile pictures, etc.) are stored. Select on Configuration > Files.', max_length=20),
        ),
    ]
