# Generated by Django 6.0.8 on 2026-09-10 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0020_apisetting_media_storage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='deposited_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount actually collected by the payment gateway for this invoice.', max_digits=14),
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short label, e.g. Net 30 or Payment on confirmation.', max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Full details of the payment terms.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who created this payment terms.', on_delete=django.db.models.deletion.CASCADE, related_name='payment_terms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EscrowAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virtual_account', models.CharField(blank=True, default='', help_text='Escrow account number shown to the customer.', max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Expected amount to be deposited.', max_digits=14)),
                ('deposited_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount actually deposited (reported by the payment gateway).', max_digits=14)),
                ('bank', models.CharField(blank=True, default='Selcom', max_length=60)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('paid', 'Paid'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.OneToOneField(blank=True, help_text='Primary invoice related to this tender/cargo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_account', to='tenders.invoice')),
                ('tender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_account', to='tenders.tender')),
                ('transporter', models.ForeignKey(blank=True, help_text='Transport company related to this escrow account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_accounts', to='tenders.transporter')),
                ('user', models.ForeignKey(help_text='Customer who posted the tender and deposits into this account.', on_delete=django.db.models.deletion.CASCADE, related_name='escrow_accounts', to=settings.AUTH_USER_MODEL)),
                ('payment_terms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_accounts', to='tenders.paymentterm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tender',
            name='payment_terms',
            field=models.ForeignKey(blank=True, help_text='Payment terms chosen by the posting user for this tender.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders', to='tenders.paymentterm'),
        ),
    ]
