# Generated by Django 6.0.8 on 2026-09-10 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0021_invoice_deposited_amount_paymentterm_escrowaccount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTermItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='A single term detail, e.g. 50% advance on confirmation.', max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_term', models.ForeignKey(help_text='Payment term this individual term belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tenders.paymentterm')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
