# Generated by Django 6.0.8 on 2026-09-10 07:07

from django.db import migrations, models


def link_existing_invoices(apps, schema_editor):
    EscrowAccount = apps.get_model('tenders', 'EscrowAccount')
    for escrow in EscrowAccount.objects.all():
        invoice_id = escrow.invoice_id
        if invoice_id is None:
            continue
        escrow.invoices.add(invoice_id)


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0022_paymenttermitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowaccount',
            name='invoices',
            field=models.ManyToManyField(blank=True, help_text='Invoices issued against this cargo reference. A cargo reference can have more than one invoice.', related_name='escrow_accounts', to='tenders.invoice'),
        ),
        migrations.RunPython(link_existing_invoices, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='escrowaccount',
            name='invoice',
        ),
    ]