# Generated by Django 6.0.8 on 2026-09-10 07:20

from django.db import migrations, models


def link_existing_transporters(apps, schema_editor):
    EscrowAccount = apps.get_model('tenders', 'EscrowAccount')
    for escrow in EscrowAccount.objects.all():
        transporter_id = escrow.transporter_id
        if transporter_id is None:
            continue
        escrow.transporters.add(transporter_id)


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0023_remove_escrowaccount_invoice_escrowaccount_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowaccount',
            name='transporters',
            field=models.ManyToManyField(blank=True, help_text='Transport companies related to this escrow account. The same cargo reference can have multiple transporters.', related_name='escrow_accounts', to='tenders.transporter'),
        ),
        migrations.RunPython(link_existing_transporters, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='escrowaccount',
            name='transporter',
        ),
    ]