# Generated by Django 6.0.8 on 2026-09-10 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0024_remove_escrowaccount_transporter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OdooCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company / Odoo instance label, e.g. ACSC Ltd.', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-safe identifier used in the per-instance webhook URL.', max_length=200, unique=True)),
                ('base_url', models.CharField(help_text='e.g. https://odoo.acsc.com', max_length=500)),
                ('auth_type', models.CharField(choices=[('none', 'No Auth'), ('bearer', 'Bearer Token'), ('basic', 'Basic Auth')], default='bearer', max_length=20)),
                ('api_token', models.CharField(blank=True, help_text='Token used for Bearer authentication', max_length=500)),
                ('username', models.CharField(blank=True, max_length=200)),
                ('password', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive companies do not appear on the webhook URL selectable list.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Odoo company',
                'verbose_name_plural': 'Odoo companies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='odoo_company',
            field=models.ForeignKey(blank=True, help_text='Odoo company/instance this order came from. Award and invoice confirmations are sent back to it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='tenders.odoocompany'),
        ),
    ]
