# Generated by Django 6.0.8 on 2026-09-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0025_odoocompany_order_odoo_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='apisetting',
            name='order_confirmation_path',
            field=models.CharField(blank=True, default='', help_text='Path order confirmations are posted to. Default: /api/v1/order-confirmation', max_length=200),
        ),
        migrations.AddField(
            model_name='apisetting',
            name='order_invoice_path',
            field=models.CharField(blank=True, default='', help_text='Path order invoices are posted to. Default: /api/v1/order-invoice', max_length=200),
        ),
        migrations.AddField(
            model_name='apisetting',
            name='partial_order_confirmation_path',
            field=models.CharField(blank=True, default='', help_text='Path partial order confirmations are posted to. Default: /api/v1/partial-order-confirmation', max_length=200),
        ),
        migrations.AddField(
            model_name='apisetting',
            name='tenders_path',
            field=models.CharField(blank=True, default='', help_text='Path tenders are posted to. Default: /api/v1/tenders', max_length=200),
        ),
        migrations.AddField(
            model_name='odoocompany',
            name='order_confirmation_path',
            field=models.CharField(blank=True, default='', help_text='Path order confirmations are posted to. Default: /api/v1/order-confirmation', max_length=200),
        ),
        migrations.AddField(
            model_name='odoocompany',
            name='order_invoice_path',
            field=models.CharField(blank=True, default='', help_text='Path order invoices are posted to. Default: /api/v1/order-invoice', max_length=200),
        ),
        migrations.AddField(
            model_name='odoocompany',
            name='partial_order_confirmation_path',
            field=models.CharField(blank=True, default='', help_text='Path partial order confirmations are posted to. Default: /api/v1/partial-order-confirmation', max_length=200),
        ),
        migrations.AddField(
            model_name='odoocompany',
            name='tenders_path',
            field=models.CharField(blank=True, default='', help_text='Path tenders are posted to. Default: /api/v1/tenders', max_length=200),
        ),
    ]
