# Generated by Django 6.0.8 on 2026-09-10 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0026_apisetting_order_confirmation_path_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiDiagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_point', models.CharField(help_text='Endpoint or integration point that produced the error.', max_length=120)),
                ('method', models.CharField(blank=True, default='GET', max_length=10)),
                ('path', models.CharField(blank=True, default='', help_text='Request path or outgoing URL.', max_length=500)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, help_text='HTTP status of the error response.', null=True)),
                ('message', models.TextField(blank=True, default='', help_text='Human-readable error message.')),
                ('detail', models.JSONField(blank=True, help_text='Extra context, e.g. the parsed error response body.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='The account that triggered the error (empty for webhook/system events).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_diagnostics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
