# Generated by Django 6.0.8 on 2026-09-10 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0027_api_diagnostic'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], db_index=True, default='pending', help_text='pending = awaiting delivery, delivered = sent, failed = permanently rejected (4xx).', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0, help_text='How many times delivery has been attempted.')),
                ('response_code', models.IntegerField(blank=True, help_text='HTTP status of the last delivery attempt.', null=True)),
                ('last_error', models.TextField(blank=True, default='', help_text='Error message of the last failed attempt.')),
                ('last_attempt_at', models.DateTimeField(blank=True, help_text='When the last delivery attempt happened.', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When the submission was finally delivered.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_pushes', to='tenders.tender')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
