# Generated by Django 6.0.8 on 2026-09-10 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0028_pendingpush'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='odoo_company',
            field=models.ForeignKey(blank=True, help_text='Transport company (Odoo instance) the tender is submitted to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders', to='tenders.odoocompany'),
        ),
    ]
