# Generated by Django 6.0.8 on 2026-09-10 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0029_tender_odoo_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='odoo_company',
        ),
        migrations.CreateModel(
            name='TenderSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, default='')),
                ('external_id', models.BigIntegerField(blank=True, null=True)),
                ('cargo_reference', models.CharField(blank=True, default='', max_length=200)),
                ('external_status', models.CharField(blank=True, default='', max_length=50)),
                ('success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('odoo_company', models.ForeignKey(help_text='Transport company (Odoo instance) the tender was submitted to.', on_delete=django.db.models.deletion.CASCADE, related_name='tender_submissions', to='tenders.odoocompany')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tenders.tender')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
