# Generated by Django 6.0.8 on 2026-09-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0030_remove_tender_odoo_company_tendersubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='apisetting',
            name='map_api_key',
            field=models.CharField(blank=True, help_text='API key for the chosen provider (MapTiler, Stadia, Thunderforest). Not needed for CARTO.', max_length=300),
        ),
        migrations.AddField(
            model_name='apisetting',
            name='map_attribution',
            field=models.CharField(blank=True, help_text='Optional copyright attribution shown on the maps. Leave blank to use the provider default.', max_length=500),
        ),
        migrations.AddField(
            model_name='apisetting',
            name='map_max_zoom',
            field=models.PositiveIntegerField(default=18, help_text='Maximum zoom level the tiles support.'),
        ),
        migrations.AddField(
            model_name='apisetting',
            name='map_provider',
            field=models.CharField(choices=[('carto', 'CARTO (free, no key)'), ('maptiler', 'MapTiler'), ('stadia', 'Stadia Maps'), ('thunderforest', 'Thunderforest'), ('custom', 'Custom tile URL')], default='carto', help_text='Map provider whose tiles are used on the tracking maps.', max_length=20),
        ),
        migrations.AddField(
            model_name='apisetting',
            name='map_tile_url',
            field=models.CharField(blank=True, help_text='Optional custom tile URL template. {APIKEY} is replaced with the API key. Leaflet placeholders {z} {x} {y} {s} {r} stay as-is.', max_length=500),
        ),
    ]
