# Generated by Django 6.0.8 on 2026-09-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0031_apisetting_map_api_key_apisetting_map_attribution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apisetting',
            name='map_api_key',
            field=models.CharField(blank=True, help_text='API key for the chosen provider (CARTO, MapTiler, Stadia, Thunderforest). CARTO keys are free at carto.com/basemaps/apikey.', max_length=300),
        ),
        migrations.AlterField(
            model_name='apisetting',
            name='map_provider',
            field=models.CharField(choices=[('carto', 'CARTO (free with API key)'), ('maptiler', 'MapTiler'), ('stadia', 'Stadia Maps'), ('thunderforest', 'Thunderforest'), ('custom', 'Custom tile URL')], default='carto', help_text='Map provider whose tiles are used on the tracking maps.', max_length=20),
        ),
    ]
