# Generated by Django 6.0.8 on 2026-09-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0032_alter_apisetting_map_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='reference',
            field=models.CharField(blank=True, help_text='Unique tender reference generated when the tender is sent. It identifies the cargo end-to-end (tender → order → invoice) and is used as the tender number.', max_length=40, null=True, unique=True),
        ),
    ]
