# Generated by Django 6.0.8 on 2026-09-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0034_backfill_tender_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='truck_alias',
            field=models.CharField(blank=True, default='', help_text='Random alias for the truck number, generated when the order is received.', max_length=40),
        ),
    ]
