# Generated by Django 6.0.8 on 2026-09-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0036_rename_cargo_reference_to_trans_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrowaccount',
            name='invoices',
            field=models.ManyToManyField(blank=True, help_text='Invoices issued against this escrow account. A tender can have more than one invoice.', related_name='escrow_accounts', to='tenders.invoice'),
        ),
        migrations.AlterField(
            model_name='escrowaccount',
            name='transporters',
            field=models.ManyToManyField(blank=True, help_text='Transport companies related to this escrow account. The same tender can have multiple transporters.', related_name='escrow_accounts', to='tenders.transporter'),
        ),
    ]
