# Generated by Django 6.0.8 on 2026-09-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0039_backfill_escrow_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttermitem',
            name='percent',
            field=models.PositiveIntegerField(blank=True, help_text='Percentage value for this term detail (e.g. 50 for a 50% advance).', null=True),
        ),
    ]
