"""
Django settings for DjangoProject project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import sys

from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9=%+j1gwd4%l7l-mbxi+dtalkp!1z90!kn=c3k+f^5un9(@nn3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS can be overridden via the environment (comma-separated).
# In development, localhost plus ngrok tunnel domains are allowed by default.
_ALLOWED_HOSTS_ENV = os.environ.get('ALLOWED_HOSTS')
if _ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS = [h.strip() for h in _ALLOWED_HOSTS_ENV.split(',') if h.strip()]
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]', '.localhost', '.ngrok-free.dev', '.ngrok.app']

# Origins allowed to submit CSRF-protected requests (e.g. POST/PUT from a
# browser). Override via the environment (comma-separated) for production.
_CSRF_TRUSTED_ORIGINS_ENV = os.environ.get('CSRF_TRUSTED_ORIGINS')
if _CSRF_TRUSTED_ORIGINS_ENV:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in _CSRF_TRUSTED_ORIGINS_ENV.split(',') if o.strip()]
else:
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost',
        'http://127.0.0.1',
        'http://[::1]',
        'https://*.ngrok-free.dev',
        'https://*.ngrok.app',
    ]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'channels',
    'users',
    'companies',
    'tenders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DjangoProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'DjangoProject.asgi.application'
WSGI_APPLICATION = 'DjangoProject.wsgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            # REDIS_URL overrides the default local Redis server (e.g. Railway).
            'hosts': [os.environ.get('REDIS_URL', ('127.0.0.1', 6379))],
        },
    },
}


def _configure_caches():
    # The test runner uses a no-op cache so tests stay deterministic and
    # independent of Redis.
    if 'test' in sys.argv:
        return {'default': {'BACKEND': 'django.core.cache.backends.dummy.DummyCache'}}
    return {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1'),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
        },
    }


CACHES = _configure_caches()

AUTH_USER_MODEL = 'users.CustomUser'

LOGIN_URL = 'users:login'
LOGIN_REDIRECT_URL = 'tenders:dashboard'
LOGOUT_REDIRECT_URL = 'users:login'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

def _configure_database():
    from django.core.exceptions import ImproperlyConfigured

    gis_engine = 'django.contrib.gis.db.backends.postgis'

    url = os.environ.get('DATABASE_URL')
    if url:
        # Hosted environments (e.g. Railway managed PostgreSQL) provide DATABASE_URL.
        return {**dj_database_url.parse(
            url,
            conn_max_age=600,
            conn_health_checks=True,
        ), 'ENGINE': gis_engine}

    host = os.environ.get('DB_HOST')
    if host:
        name = os.environ.get('DB_NAME')
        user = os.environ.get('DB_USER')
        missing = [key for key, value in (('DB_NAME', name), ('DB_USER', user)) if not value]
        if missing:
            raise ImproperlyConfigured(
                'TCP database configuration missing required environment variables: '
                + ', '.join(missing)
            )
        return {
            'ENGINE': gis_engine,
            'NAME': name,
            'USER': user,
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': host,
            'PORT': os.environ.get('DB_PORT') or None,
            'CONN_MAX_AGE': 600,
            'CONN_HEALTH_CHECKS': True,
        }

    # Local development: PostgreSQL over the default socket with peer auth.
    for socket_path in ('/var/run/postgresql/.s.PGSQL.5432', '/tmp/.s.PGSQL.5432'):
        if os.path.exists(socket_path):
            return {
                'ENGINE': gis_engine,
                'NAME': os.environ.get('DB_NAME', 'django_project'),
                'USER': os.environ.get('DB_USER', 'leon'),
                'PASSWORD': os.environ.get('DB_PASSWORD', ''),
                'CONN_MAX_AGE': 600,
                'CONN_HEALTH_CHECKS': True,
            }

    raise ImproperlyConfigured(
        'Database is not configured. '
        'Set DATABASE_URL (preferred, e.g. Railway managed PostgreSQL) or, for a TCP connection, '
        'DB_HOST together with DB_NAME, DB_USER and DB_PASSWORD.'
    )


DATABASES = {'default': _configure_database()}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / 'static']


# Media files (user uploads, e.g. profile pictures)
# https://docs.djangoproject.com/en/6.1/topics/files/

MEDIA_URL = 'media/'

MEDIA_ROOT = BASE_DIR / 'media'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'HYPAX <no-reply@hypax.local>'
