# Generated by Django 6.0.8 on 2026-09-07 20:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='agents',
            field=models.ManyToManyField(blank=True, help_text="Agents that can see this transporter's tenders and invoices", related_name='linked_transporters', to=settings.AUTH_USER_MODEL),
        ),
    ]
