# Generated by Django 6.0.8 on 2026-09-07 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_agents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='agents',
        ),
    ]
