# Generated by Django 6.0.8 on 2026-09-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_remove_company_agents'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tin',
            field=models.CharField(blank=True, help_text='Tax Identification Number (TIN)', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='vat',
            field=models.CharField(blank=True, help_text='Value Added Tax (VAT) number', max_length=100),
        ),
    ]
