# Generated by Django 6.0.8 on 2026-09-10 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_tin_company_vat'),
        ('tenders', '0027_api_diagnostic'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='odoo_company',
            field=models.ForeignKey(blank=True, help_text='The Odoo company/instance this transporter posts its tenders to. Tenders are submitted to its base URL when linked.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_companies', to='tenders.odoocompany'),
        ),
    ]
