# Generated by Django 6.0.8 on 2026-09-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_odoo_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='odoo_company',
        ),
    ]